.PHONY: all clean
.DEFAULT: all

all:
	$(MAKE) -C hash_table all
#	$(MAKE) -C queue all
#	$(MAKE) -C search_tree all
	$(MAKE) -C vector all

clean:
	$(MAKE) -C hash_table clean
#	$(MAKE) -C queue clean
#	$(MAKE) -C search_tree clean
	$(MAKE) -C vector clean
